export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_TOKEN = "SET_TOKEN";

export const SET_LOADING = "SET_LOADING";
export const CLEAR_UI = "CLEAR_UI";
export const SET_NEXT_PAGE = "SET_NEXT_PAGE"